### ISSUE TITLE
http://newsite.clownatec.com/birthday-contact-us/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#1]
Bonjour Christian ,
J'ai mis la nouvelle form
peux tu arranger les scripts suivants

-
- [ ] mobile  phone: le format (xxx)xxx xxxx et s'il manque un chiffre pour dire qu'il est invalide

- [x] Home and work phone le format (xxx)xxx xxxx et s'il manque un chiffre pour dire qu'il est invalide

- [x] Show start time peux tu avoir l'air de cela,  (heure, minute vide avec la flèche)
![capture time](https://cloud.githubusercontent.com/assets/3742270/21754065/667ccd98-d5c6-11e6-81c9-a14a30a4d61a.PNG)

- [x] Date of event : mettre le calendrier

- [x] How did you find out of clownatec ne fonctionne pas du tout

Merci

**Comment by cmarois** [comment]
Michelle, Je vais avoir besoin de ton aide, pour les telephones invalide.   Il y a des options dans la form submit maintenant, pour avoir des required fields, et je vois qu'il y a une option pour verifier le format du email.   Il doit surement y avoir une option pour verifier le format des telephone.  Mais elle n'etait pas selectionée et je ne sais pas c'est quoi.    Il faudrait, dans 1shoppingcart, aller ou tu specifie quel fields sont required, et checker pour l'option du format de telephone.   Apres, en obtenant le code de la form, on va avoir l'option du format

**Comment by Clownatec01** [comment]
Bonjour Christian 
la semaine dernière j'étais en conférence...

- [ ] pour te show time Show start time est ce possible d'avoir  le 2 première case vide (comme l'image plus haut. pour qu'il choissise le temps au lieu d'avoir 12 : 00

- [ ] Le calendrier doit etre en anglais

Je ne suis pas certaine si je comprends pour le téléphone...

 start time peux tu avoir l'air de cela, (heure, minute vide avec la flèche)

**Comment by Clownatec01** [comment]
Bonjour christian
j'ai vérifier pour le téléphone il y a pas d'option pour vérifier si le téléphone et valide mais c'est correct on peu laisser faire s'il y a un problem je contacterai le client par email. 

- [ ] mais 
 est ce possible de le mettre le format XXX-XXX-XXXX pour que ce soit plus facile a lire

- [ ] peut tu arranger la form pour que ce soit 2 colum (shopping cart offre pas cette option)

**Comment by cmarois** [comment]
Le telephone devrait etre deja formatté (en tous cas ici il l'est)
Pour la validité, vu que 1shoppingcart verifie les mandatory et etc avec le post, c'est difficile pour moi de verifier la validité sur le 'submit'   Mais l'autre chose c'est que je pourrais peut-etre le verifier quand on sort du champ.   Je crois que je voulais juste pas re-inventer la roue si c'etait deja pris en charge par 1shoppingcart.

**Comment by Clownatec01** [comment]
super le téléphone est formaté je fesais des test avec 1112223333 et cela fontionnait pas mais avec 819 ou 613 cela fonctionne cool

**Comment by Clownatec01** [comment]
![image](https://cloud.githubusercontent.com/assets/3742270/22714146/38923a1c-ed59-11e6-9aa3-ecbdc364545a.png)

pour le heure  j'ai une line de code peux -tu me dire si c'est correct
![image](https://cloud.githubusercontent.com/assets/3742270/22714134/2b4c005e-ed59-11e6-8422-89908ee75254.png)
