### ISSUE TITLE
http://newsite.clownatec.com/school-e-promo-kit/.php

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#24]
- [x] Petit  problème l'information préfield est la si je scroll down mais si je pèse sur un des bouton (Book now) que j'ai redirigé au bas de la page à la form tout les préfields disparaisse

- [x] le  script pour Is the location easy to find on Google maps? ne fonctionne pas

- [x] peux  tu aligner ces 2 fields
![image](https://cloud.githubusercontent.com/assets/3742270/23933841/af2c4a08-0917-11e7-97b0-ab2ab865d3ed.png)

- [x] peux-tu  sois centrer la form avec la partie du haut ou bien la mettre la même largeur pour que ce soit plus beau. (je l'ai élargie a 940px) on dirait que l'entertainment option de place mieux

- [x] peux tu arranger la mise en page des entertainment options j'aimerais quelle soit comme on avait, bleu plus large et le plus a coté
![image](https://cloud.githubusercontent.com/assets/3742270/23948612/2d72191e-095a-11e7-9ba1-e17e157c3fa4.png)

- [x] N'oublile pas de faire le script pour faire disparaitre Location Name s'il coche use School adress

- [x] J'ai ajouter les * mais les requires field ne fontionne pas

**Comment by Clownatec01** [comment]
Tout les problèmes plus haut tu me dira comment les faires car je vais devoir les faires sur daycare et corporatif

**Comment by Clownatec01** [comment]
- [ ] As tu trouver comment arranger les heures qui apparaisse completement en bas au lieu que le drop down apparaisse dans la case qu,on click

**Comment by Clownatec01** [comment]
- [ ] est-ce possible d'arranger la mise en page pour que ce soit plus comme l'ancienne form, elle est plus arréer et dégager
![image](https://cloud.githubusercontent.com/assets/3742270/23973991/369b0adc-09af-11e7-8bd7-00efd55c0c9f.png)
voici la nouvelle pour que tu vois la comparaison.  tu peux changer la font s'il faut

**Comment by cmarois** [comment]
TEst Github

**Comment by cmarois** [comment]
Tout fait.

**Comment by Clownatec01** [comment]
![image](https://cloud.githubusercontent.com/assets/3742270/24073295/d1528e74-0bcb-11e7-8d38-1019c6989926.png)

- [ ] 1. peux-tu mettre un peu plus d'espace entre les colonne

- [ ] 2 . peux-tu mettre la case bleu plus large (verticalement)

**Comment by cmarois** [comment]
fait

**Comment by Clownatec01** [comment]
parfait
