### ISSUE TITLE
http://newsite.clownatec.com/daycare-e-promo-kit/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#25]
![image](https://cloud.githubusercontent.com/assets/3742270/23978145/b5af9f36-09c8-11e7-9a20-7a06dd22155c.png)

- [x] 1. changer le titre Fun Entertainement

- [x] Enlever cette section il en a pas pour daycare
ces changements sont pour daycare

**Comment by cmarois** [comment]
fait

**Comment by Clownatec01** [comment]
peux tu les centrer merci
![image](https://cloud.githubusercontent.com/assets/3742270/24080815/c6b3b87e-0c7c-11e7-8249-d60a1a1a376e.png)

**Comment by cmarois** [comment]
http://test.com?test=1&test=2

**Comment by cmarois** [comment]
fait

**Comment by Clownatec01** [comment]
merci
