### ISSUE TITLE
http://newsite.clownatec.com/school-e-promo-kit/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#30]
La field time of day ne transferai pas du e-promo vers la base de donné 
je crois qu'il manquait input ....
  <input  id="timeofday" type="hidden" name="timeofday" value="">

peux tu vérifier si je l'ai mis a la bonne place

**Comment by cmarois** [comment]
Quand un input est hidden tu peux le mettre n'importe ou, l'important c'est qu'il soit dans le html a qqpart.

donc c'est correct
