### ISSUE TITLE
http://newsite.clownatec.com/school-e-promo-kit/review-your-booking/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#33]
![image](https://cloud.githubusercontent.com/assets/3742270/24087823/1f9ef16a-0cfa-11e7-9c22-1b7efa273d08.png)
pourrais tu arrager I agree similaire ! a celui dans haut (grosseur, couleur #555 font open sans)
et centrer la phrase  et le button

**Comment by cmarois** [comment]
fait
