### ISSUE TITLE
http://newsite.clownatec.com/ecole-e-promo-kit/verification-de-reservation/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#34]
![image](https://cloud.githubusercontent.com/assets/3742270/24088568/4c5e9734-0d02-11e7-906d-e71ad388c3ce.png)
je présume que les prix apparait pas car la table est pas terminé
![image](https://cloud.githubusercontent.com/assets/3742270/24088582/771ac4d4-0d02-11e7-96d8-3efe6c32c538.png)
peux tu arranger la phrase pour quelle soit le meme style que celle plus haut (opens sans 18px, color #555) et center
peux tu center le boutton aussi

**Comment by cmarois** [comment]
J'ai fait le formatting des boutons, sur les deux pages  last minute  (francais et anglais).

**Comment by cmarois** [comment]
La raison pour laquelle tu n'as pas de prix dans la table, c'est que tu es sur la page francaise et les options sont en anglais.  il les trouve pas.

**Comment by Clownatec01** [comment]
Je croyais que si je changais le nom que cela fonctionnerais alors dis moi ce que je dois faire
![image](https://cloud.githubusercontent.com/assets/3742270/24133444/67b1ba76-0dd3-11e7-8d70-a8f36e32e731.png)

**Comment by cmarois** [comment]
Oui,  ce que tu as fais c'est correct.
Le probleme n'est pas sur verification.   Le probleme c'est que tu as probablement parti d'un test direct de 1shoppingcart avec des options deja choisi en anglais.

Faudrait que tu commence ton test en francais a partir de la e-promo-kit francaise.

**Comment by Clownatec01** [comment]
super merci
