### ISSUE TITLE
http://newsite.clownatec.com/school-e-promo-kit/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#36]
- [x] J'aimerais 
 avoir les boites rouges pour les requires field...

- [x] il  me laisse sousmettre et me dit seulment au capcha qu'il me manque des infos j'aimerais que les boites rouge apparaisse et qu'il me laisse pas passé

**Comment by cmarois** [comment]
Je crois que j'ai trouver pourquoi il ne restait pas sur la form.

**Comment by cmarois** [comment]
Oups.. j'ai regler pour Birthday. pas pour school .  m'a checker school

**Comment by cmarois** [comment]
Ok.  School Epromo kit fonctionne.
