### ISSUE TITLE
http://newsite.clownatec.com/cpe-et-garderie-e-promo-kit/verification-de-reservation/.php/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#44]
il laisse passer sans que je coche la boite

**Comment by cmarois** [comment]
Reglé

**Comment by Clownatec01** [comment]
il me laisse passé encore

**Comment by cmarois** [comment]
Les changements que j'ai fait pour les boites rouges et le scroll on introduit le bug.

C'est reglé
