### ISSUE TITLE
http://newsite.clownatec.com/ecole-q-r-complete/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#47]
![image](https://cloud.githubusercontent.com/assets/3742270/24822427/2311c20a-1bc3-11e7-92a8-cea780e3ab52.png)
J'ai copier cela de la partie anglais mais il a un probleme  certain code apparait
http://newsite.clownatec.com/school-all-faq/

**Comment by cmarois** [comment]
Je les vois pas.  est-ce que tu as regler?      Sinon, c'est dans les 'custom html'  des lignes d'extra qui sont considerer comme du texte.

**Comment by Clownatec01** [comment]
Je l'ai réglé
