### ISSUE TITLE
http://newsite.clownatec.com/ecole-e-promo-kit/verification-de-reservation/.php

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#48]
accent 
pars de la web form transfer correctement dans la base de donné
e-promo kit (accent transfer)
email lien les accents ne transfer pas
Je vais t'envoyer un test avec lien

**Comment by cmarois** [comment]
Peux-tu reessayer? (de la e-promo-kit)

J'ai changer de quoi dans la table de la e-promot

Si ca fonctionne, je vais changer les autres francais.

**Comment by Clownatec01** [comment]
cela semble fonctionné car je suis meme aller dans review your booking et mes accent sont la
