### ISSUE TITLE
test school ang accent

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#51]
Les deux plante a la même place

web form a database transfert (database correct)
web form au e-promo transfert (database correct)
data base au email transfert (database correct)
email lien au e-promo transfert (database correct)
event quote email transfert 
event quote email link to quote page transfer (database correct)
le problem est ici quand je submit la les accent le transfert pas dans la database

**Comment by cmarois** [comment]
ca c'est les accents que tu rentre dans le champs?  genre nom prenom etc?

**Comment by Clownatec01** [comment]
oui pour tester j'ai mis 
prénom: Michà
nom famille: lafè
compagnie Clownaté

**Comment by Clownatec01** [comment]
J'ai retester ecole fr et cela semble fonctionné car la je me rend au review et je perd pas mes accents

**Comment by Clownatec01** [comment]
comprend plus rien si tu as rien fait je viens de tester schoolang et je garde mes accents...

**Comment by cmarois** [comment]
J'ai rien fait pour ce problem, je m'apprete a checker.

**Comment by cmarois** [comment]
Je viens de changer qqchose,  tu peux-reessayer.    Lis mon email que je viens d'envoyer pour les info supplementaires.

**Comment by Clownatec01** [comment]
definitivement j'ai vérifier et le charset=UTF-8 mais la je perds mes accents quand je sousmet la quote...

**Comment by cmarois** [comment]
Ok,  J'ai enlever le parametre  charset  totalement.    Peux-tu reverifier?    Ca, ca va prendre le default du browser, ici c'est ISO 8859-1.   

On va voir ce que ca va faire.
