### ISSUE TITLE
http://newsite.clownatec.com/corporatif-e-promo-kit/.php

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#55]
![image](https://cloud.githubusercontent.com/assets/3742270/24915982/c5f64f1e-1ea6-11e7-9c63-81bdd8bbe656.png)
enlever 
maquillage
clown 
ventriloquie
J'ai corrigé mon image dans le e-promo-kit

**Comment by cmarois** [comment]
fait
