### ISSUE TITLE
http://newsite.clownatec.com/birthday-parents-reviews/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#6]
pourrais tu arranger cela

- [x] How did you find out about clownatec ne fonctionne pas et peux tu enlever l'option yellow page

- [x] Est-ce possible quand il select multi que la field 2 child first name devienne obligatoire et avec un *

- [x] il y a 2 form une en dessous de l'autre je comprend pas...

**Comment by cmarois** [comment]
Pour la deuxieme form.  j'en ai aucune idée.  
Par contre, voici ce que je peux dire:
- Ce n'est pas le code de la form en tant que tel.
- Il y a une premiere 'form' dans la vrai page qui est dans un tag <code></code>  et apres, il y a la deuxieme form juste après.  

Je commencerais par checker si il n'y a pas une genre d'option selectionnée dans la form generation dans 1 shopping cart, ou bien où tu as generé la form la premiere fois..

**Comment by Clownatec01** [comment]
J'ai trouvé pour la 2ième form c'est arrangé 
parcontre je crois que j'ai brisé le code

- [ ] Il y a l'astérix pour la field 2 child name mais peux tu la rendre obligatoire quand elle apparait 
merci et ecuse-moi
