### ISSUE TITLE
E-promo kit

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#60]
est-ce qu'il y a une façon de m'assurer qu'il ont fait au moins un choix de diverstissement avant qu'il puisse soumettre 
ce serait pour tout les e-promo ANG et FR

**Comment by cmarois** [comment]
Oui... Maintenant que j'ai fait le code pour les 'selects'  sky is the limit.

**Comment by Clownatec01** [comment]
peux tu le mettre sur tout les e-promo kit

**Comment by cmarois** [comment]
J'ai une autre question:   L'addresse pour le show, est required aussi,   je peux mettre la boite rouge autour de ca aussi  (à coté de location name)

**Comment by Clownatec01** [comment]
Tu as bien raison et il faut qu'il disparaisse s'il coche same adress

**Comment by Clownatec01** [comment]
Il me reste passer même si je fais pas de choix de divertissement
http://newsite.clownatec.com/school-e-promo-kit/ 
http://newsite.clownatec.com/ecole-e-promo-kit/
http://newsite.clownatec.com/daycare-e-promo-kit/
http://newsite.clownatec.com/cpe-et-garderie-e-promo-kit/
http://newsite.clownatec.com/corporate-e-promo-kit/
http://newsite.clownatec.com/corporatif-e-promo-kit/
