### ISSUE TITLE
http://newsite.clownatec.com/ecole-e-promo-kit/.php

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#61]
![image](https://user-images.githubusercontent.com/3742270/27516925-0d0fcaa4-5991-11e7-847d-33171537683a.png)

- [x] peux  tu changer l'ordre de la premiere colone car j'aimerais être uniform dans toute mes table

- [x] peux tu changer le titre divertissement de cours d'école pour animation de foule

**Comment by cmarois** [comment]
fait
