### ISSUE TITLE
http://newsite.clownatec.com/school-e-promo-kit/.php

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#62]
![image](https://user-images.githubusercontent.com/3742270/27516960-9ad67d38-5991-11e7-8de0-fd0917e7764f.png)

- [x] peux tu changer l'ordre de la première colone car je voudrais etre uniform dans toute mes table (eater va etre en 7  et santa en 8 ieme)

- [x] peux tu changer l'ordre de la dernière colone

**Comment by cmarois** [comment]
fait
