### ISSUE TITLE
http://newsite.clownatec.com/birthday-e-promo-kit/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#79]
- [ ] J'ai  besoin du script pour qu'il mettre le nom de l'enfant fêté et s'il sont plusieurs mettre les 2

- [ ] J'ai besoin aussi du script qui permet de changer le text his pour her et them..

**Comment by Clownatec01** [comment]
- [ ] peux tu centrer la form

- [ ] besoin asterix et boite rouge
Fist  Name (préfield)
Last name (prefield)
 work phone (changer pour Primary Phone)
Homephone ( changer pour Secondary Phone )
Adress1 (changer pour Home Adress)
City
State
Zip (changer pour Postal Code)
child Last name (prefield)
Date of birth (peux tu mettre un calendrier seulement avec les mois pas l'annné
année (peux tu mettre choisir l'année et qu'il soit obligé dans choisir une)
child gender (préfield)
Event location tous sauf google oublie pas de faire disparaitre la location name s,il coche same as home adress
Party information tous

**Comment by cmarois** [comment]
j'arrive plus a editer la page... ca dit que la memoire est excedée dans la database

**Comment by Clownatec01** [comment]
la page est corrompue j'ai tout enlever excepter la form et j'ai la même erreur  utilise cette page pour faire les changement demander (dup) Birthday E-Promo-Kit
confirme moi que tu as vu ce message et je vais aller enlever la page original et la remplacer par celle la (dup) Birthday E-Promo-Kit car je voulais pas l'enlever avant que tu la vois

**Comment by cmarois** [comment]
J'ai vu le message

Envoyé de mon iPhone

**Comment by Clownatec01** [comment]
tu peux travailler dessus j'ai effacer la page corompu

**Comment by cmarois** [comment]
J'ai pas checker pour les mandatory pour le deuxieme enfant,  m'a faire ca prochainement,  mais pour un enfant,  tu peux tester.
