### ISSUE TITLE
http://newsite.clownatec.com/fete-enfants-parents-temoignages/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#81]
peux tu mettre la boite rouge quand elle apparait
![image](https://user-images.githubusercontent.com/3742270/28198454-4f6916d6-682c-11e7-99a0-3b46ca44dab2.png)

**Comment by Clownatec01** [comment]
peux tu arrangé pour qu'il est un peu moins d'espace entre les questions

**Comment by Clownatec01** [comment]
dans le pop up 
 change le titre pour 
Renseignements sur les forfaits et les prix.

N’attendez pas, complétez la fiche ci-dessous pour visualiser IMMÉDIATEMENT les prix et forfaits qui répondent à VOS besoins, pour réaliser les rêves de VOTRE enfant!

**Comment by cmarois** [comment]
fait pour les 2 derniers.
