### ISSUE TITLE
http://newsite.clownatec.com/birthday-e-promo-kit/birthday-last-minute-details/

### ISSUE THREAD

**Issue by Clownatec01** [cmarois/newsite#86]
question pour toi comment je m'y prend pour que les gens click sur le lien et puisse downloader et imprimer le poster
sur l'autre site quand je click sur le lien l'image apparrait et le url c'est
http://clownottawa.com/wp-content/uploads/2013/04/Poster-Homeshow-Kitty.pdf

![image](https://user-images.githubusercontent.com/3742270/28241683-24aa6f94-6967-11e7-99ab-d996f782ee7d.png)

**Comment by cmarois** [comment]
Si tu veux dire qu'en cliquant sur le lien, il te demande de 'downloader' a la place d'ouvrir dans adobe,  tu peux pas,  et c'est pas recommandé.  

par contre, dans adobe, tu as des boutons pour downloader, etc..

**Comment by Clownatec01** [comment]
non je veux qu'il l'ouvre dans adobe
mais je veux savoir pour le nouveau site J'ai plein de document 
est-ce que je préprare les documents et on les uploade avec le ftp  dans un dossier special ???

**Comment by cmarois** [comment]
Ok.  
Ton commentaire me fait penser a quelque chose. 

Mais premierement. si tes liens sont fichiers .PDF,  c'est tres difficile de les faire downloader, parce que tu te bas contre des standards etabli (la maniere dont les programmes fonctionnent), et pour ne pas que ton browser ouvre le fichier, mais le download, c'est pas au niveau du browser que ca se fait (html/javascript), c'est au niveau du serveur, enveler les configurations pour les pdf etc,  et la on joue dans l'electricité les 2 pieds dans l'eau.

PAR CONTRE:   Si tu mets tes PDF dans des .zip,   la il va te demander de les downloader, parce que c'est l'action par default pour les zip files.  Tu peux mettre un pdf par zip, ou les mettres tous, ou comme tu veux.    La y aurais pas de problemes.

**Comment by Clownatec01** [comment]
pas certain que je comprends dans le fond moi j'ai besoin que le client puisse ajouter des info et l'imprimer 
alors je croyais que avec adobe il pouvait mettre les info et les imprimer. il ont pas besoin de downloader le document.

**Comment by cmarois** [comment]
Tu as ecris ca: "_question pour toi comment je m'y prend pour que les gens click sur le lien et puisse downloader_"

et la tu me dit qu'ils ont pas besoin de downloader...


Je crois que le probleme que tu veux me dire c'est que quand tu click sur le 'ENG' ou 'FR' il ouvre pas le pdf, mais il re-ouvre la page ou on est.
Ce qui est un different probleme de ce que tu enonce en haut. Ca c'est qqchose que je peux regarder..

**Comment by cmarois** [comment]
Il faut que tu mette les references aux fichiers dans tes hyperliens.

Je te conseil ceci: 

Met tes poster dans un dossier sur Clownatec.com  (par exemple le lien du poster que t'as mis en haut est sur clownottawa.com).    Comme ca quand on va changer le site de place (de newsite a ... clowatec) les liens vont toujours fonctionner.

Ensuite, vas dans optimize press, edit les sections qui sont "ENG | FR".   Click sur ENG ou FR, un petit menu apparait,  click sur le crayon 'edit' et entre le lien du fichier.
Par exemple, "  http://clownatec.com/_<le dossier ou tu as mis tes fichiers>_/_<le nom du fichier>_.pdf  "

La il devrait ouvrir ta page.

**Comment by Clownatec01** [comment]
est-ce que je pourrais mettre un dossier documents client et mettre tous dedans

**Comment by cmarois** [comment]
ouais  tu choisis le nom que tu veux, et on va aller les chercher ou ils sont.

**Comment by Clownatec01** [comment]
super
